#!/usr/bin/env bash
set -euo pipefail

mobile_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${mobile_root}"

wrapper_jar="android/gradle/wrapper/gradle-wrapper.jar"
wrapper_properties="android/gradle/wrapper/gradle-wrapper.properties"

if [[ -x android/gradlew && -f "${wrapper_jar}" && -f "${wrapper_properties}" ]]; then
  exit 0
fi

if ! command -v flutter >/dev/null 2>&1; then
  echo "Flutter is required to regenerate the Android Gradle wrapper." >&2
  exit 1
fi

if ! command -v git >/dev/null 2>&1 || ! git rev-parse --show-toplevel >/dev/null 2>&1; then
  echo "A Git checkout is required to preserve the tracked Android configuration." >&2
  exit 1
fi

if [[ -n "$(git status --short -- android)" ]]; then
  echo "Refusing to regenerate the Android wrapper while Android files have local changes." >&2
  exit 1
fi

wrapper_tmp="$(mktemp -d)"
trap 'rm -rf "${wrapper_tmp}"' EXIT

flutter create \
  --platforms=android \
  --project-name=moataz_ai_mobile \
  --org=com.moataz \
  --no-pub \
  .

if [[ ! -x android/gradlew || ! -f "${wrapper_jar}" || ! -f "${wrapper_properties}" ]]; then
  echo "Flutter did not generate a complete Android Gradle wrapper." >&2
  exit 1
fi

# Preserve only the wrapper generated by the pinned Flutter toolchain. Remove any
# additional Android scaffolding before restoring the project's tracked files.
mkdir -p "${wrapper_tmp}/gradle/wrapper"
cp android/gradlew "${wrapper_tmp}/gradlew"
cp android/gradlew.bat "${wrapper_tmp}/gradlew.bat"
cp "${wrapper_jar}" "${wrapper_tmp}/gradle/wrapper/gradle-wrapper.jar"
cp "${wrapper_properties}" "${wrapper_tmp}/gradle/wrapper/gradle-wrapper.properties"

git restore --source=HEAD --worktree -- android
git clean -fd -- android >/dev/null

mkdir -p android/gradle/wrapper
cp "${wrapper_tmp}/gradlew" android/gradlew
cp "${wrapper_tmp}/gradlew.bat" android/gradlew.bat
cp "${wrapper_tmp}/gradle/wrapper/gradle-wrapper.jar" "${wrapper_jar}"
cp "${wrapper_tmp}/gradle/wrapper/gradle-wrapper.properties" "${wrapper_properties}"
chmod +x android/gradlew
