DO $$ BEGIN CREATE TYPE "member_role" AS ENUM ('owner','admin','developer','operator','viewer'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE "agent_status" AS ENUM ('draft','published','archived'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE "run_status" AS ENUM ('queued','running','waiting_for_approval','completed','failed','cancelled'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE "provider_kind" AS ENUM ('openai','anthropic','gemini'); EXCEPTION WHEN duplicate_object THEN null; END $$;

CREATE TABLE IF NOT EXISTS "organizations" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "name" text NOT NULL, "slug" text NOT NULL UNIQUE, "created_at" timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS "users" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "email" text NOT NULL UNIQUE, "name" text, "created_at" timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS "organization_members" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "organization_id" uuid NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE, "user_id" uuid NOT NULL REFERENCES "users"("id") ON DELETE CASCADE, "role" member_role NOT NULL DEFAULT 'viewer', "created_at" timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS "organization_members_org_user_idx" ON "organization_members" ("organization_id", "user_id");
CREATE TABLE IF NOT EXISTS "platform_api_keys" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "organization_id" uuid NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE, "name" text NOT NULL, "key_hash" text NOT NULL UNIQUE, "key_prefix" text NOT NULL, "revoked" boolean NOT NULL DEFAULT false, "last_used_at" timestamptz, "created_at" timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS "provider_credentials" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "organization_id" uuid NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE, "provider" provider_kind NOT NULL, "name" text NOT NULL, "encrypted_secret" text NOT NULL, "secret_hint" text NOT NULL, "enabled" boolean NOT NULL DEFAULT true, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS "agents" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "organization_id" uuid NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE, "name" text NOT NULL, "description" text, "status" agent_status NOT NULL DEFAULT 'draft', "current_version" integer NOT NULL DEFAULT 1, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS "agent_versions" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "agent_id" uuid NOT NULL REFERENCES "agents"("id") ON DELETE CASCADE, "version" integer NOT NULL, "provider_credential_id" uuid NOT NULL REFERENCES "provider_credentials"("id"), "model" text NOT NULL, "instructions" text NOT NULL, "temperature_milli" integer NOT NULL DEFAULT 200, "max_output_tokens" integer NOT NULL DEFAULT 2048, "max_model_calls" integer NOT NULL DEFAULT 8, "max_tool_calls" integer NOT NULL DEFAULT 12, "tools" jsonb NOT NULL DEFAULT '[]'::jsonb, "created_at" timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS "agent_versions_agent_version_idx" ON "agent_versions" ("agent_id", "version");
CREATE TABLE IF NOT EXISTS "conversations" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "organization_id" uuid NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE, "agent_id" uuid NOT NULL REFERENCES "agents"("id") ON DELETE CASCADE, "title" text, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS "messages" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "conversation_id" uuid NOT NULL REFERENCES "conversations"("id") ON DELETE CASCADE, "role" text NOT NULL, "content" text NOT NULL, "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb, "created_at" timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS "runs" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "organization_id" uuid NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE, "agent_id" uuid NOT NULL REFERENCES "agents"("id"), "agent_version_id" uuid NOT NULL REFERENCES "agent_versions"("id"), "conversation_id" uuid REFERENCES "conversations"("id"), "status" run_status NOT NULL DEFAULT 'queued', "input" text NOT NULL, "output" text, "error" text, "provider" provider_kind NOT NULL, "model" text NOT NULL, "input_tokens" integer NOT NULL DEFAULT 0, "output_tokens" integer NOT NULL DEFAULT 0, "started_at" timestamptz, "completed_at" timestamptz, "created_at" timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS "run_events" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "run_id" uuid NOT NULL REFERENCES "runs"("id") ON DELETE CASCADE, "sequence" integer NOT NULL, "type" text NOT NULL, "payload" jsonb NOT NULL DEFAULT '{}'::jsonb, "created_at" timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS "audit_logs" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "organization_id" uuid REFERENCES "organizations"("id") ON DELETE CASCADE, "actor_type" text NOT NULL, "actor_id" text, "action" text NOT NULL, "resource_type" text NOT NULL, "resource_id" text, "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb, "created_at" timestamptz NOT NULL DEFAULT now());

CREATE INDEX IF NOT EXISTS "agents_organization_idx" ON "agents" ("organization_id");
CREATE INDEX IF NOT EXISTS "runs_organization_created_idx" ON "runs" ("organization_id", "created_at" DESC);
CREATE INDEX IF NOT EXISTS "run_events_run_sequence_idx" ON "run_events" ("run_id", "sequence");
CREATE INDEX IF NOT EXISTS "audit_logs_org_created_idx" ON "audit_logs" ("organization_id", "created_at" DESC);
