CREATE TABLE IF NOT EXISTS "platform_runtime_settings" (
  "id" text PRIMARY KEY NOT NULL,
  "whatsapp_managed" boolean DEFAULT false NOT NULL,
  "whatsapp_enabled" boolean DEFAULT false NOT NULL,
  "whatsapp_config_encrypted" text,
  "whatsapp_connect_ttl_minutes" integer DEFAULT 10 NOT NULL,
  "sandbox_managed" boolean DEFAULT false NOT NULL,
  "sandbox_enabled" boolean DEFAULT false NOT NULL,
  "sandbox_runner_url" text,
  "sandbox_runner_secret_encrypted" text,
  "sandbox_execution_timeout_ms" integer DEFAULT 300000 NOT NULL,
  "sandbox_max_output_bytes" integer DEFAULT 2097152 NOT NULL,
  "sandbox_max_file_bytes" integer DEFAULT 10485760 NOT NULL,
  "sandbox_workspace_disk_bytes" integer DEFAULT 536870912 NOT NULL,
  "sandbox_max_concurrent_per_org" integer DEFAULT 2 NOT NULL,
  "browser_managed" boolean DEFAULT false NOT NULL,
  "browser_enabled" boolean DEFAULT false NOT NULL,
  "browser_runner_url" text,
  "browser_runner_secret_encrypted" text,
  "browser_interactive_login_enabled" boolean DEFAULT false NOT NULL,
  "browser_screenshots_enabled" boolean DEFAULT true NOT NULL,
  "browser_task_timeout_ms" integer DEFAULT 300000 NOT NULL,
  "browser_max_steps" integer DEFAULT 50 NOT NULL,
  "browser_max_pages" integer DEFAULT 5 NOT NULL,
  "browser_allowed_download_bytes" integer DEFAULT 10485760 NOT NULL,
  "updated_by_user_id" uuid REFERENCES "users"("id") ON DELETE SET NULL,
  "last_health" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "platform_runtime_settings_whatsapp_ttl_check" CHECK ("whatsapp_connect_ttl_minutes" BETWEEN 5 AND 60),
  CONSTRAINT "platform_runtime_settings_sandbox_timeout_check" CHECK ("sandbox_execution_timeout_ms" BETWEEN 1000 AND 1800000),
  CONSTRAINT "platform_runtime_settings_sandbox_output_check" CHECK ("sandbox_max_output_bytes" BETWEEN 1024 AND 20971520),
  CONSTRAINT "platform_runtime_settings_sandbox_file_check" CHECK ("sandbox_max_file_bytes" BETWEEN 1024 AND 104857600),
  CONSTRAINT "platform_runtime_settings_sandbox_disk_check" CHECK ("sandbox_workspace_disk_bytes" BETWEEN 10485760 AND 10737418240),
  CONSTRAINT "platform_runtime_settings_sandbox_concurrency_check" CHECK ("sandbox_max_concurrent_per_org" BETWEEN 1 AND 20),
  CONSTRAINT "platform_runtime_settings_browser_timeout_check" CHECK ("browser_task_timeout_ms" BETWEEN 10000 AND 1800000),
  CONSTRAINT "platform_runtime_settings_browser_steps_check" CHECK ("browser_max_steps" BETWEEN 1 AND 100),
  CONSTRAINT "platform_runtime_settings_browser_pages_check" CHECK ("browser_max_pages" BETWEEN 1 AND 10),
  CONSTRAINT "platform_runtime_settings_browser_download_check" CHECK ("browser_allowed_download_bytes" BETWEEN 1024 AND 104857600)
);

CREATE INDEX IF NOT EXISTS "platform_runtime_settings_updated_idx"
  ON "platform_runtime_settings" ("updated_at");
