import {
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";
import {
  agents,
  agentTeamRuns,
  mcpServers,
  mcpTools,
  organizations,
  providerCredentials,
  runs,
  toolApprovalStatus,
  users,
} from "@/db/schema";

export const agentRunSteps = pgTable("agent_run_steps", {
  id: uuid("id").defaultRandom().primaryKey(),
  organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  runId: uuid("run_id").notNull().references(() => runs.id, { onDelete: "cascade" }),
  stepNumber: integer("step_number").notNull(),
  stepType: text("step_type").notNull(),
  status: text("status").notNull(),
  model: text("model"),
  providerCredentialId: uuid("provider_credential_id").references(() => providerCredentials.id, { onDelete: "set null" }),
  toolCallId: text("tool_call_id"),
  toolId: uuid("tool_id").references(() => mcpTools.id, { onDelete: "set null" }),
  inputDigest: text("input_digest"),
  outputDigest: text("output_digest"),
  inputTokens: integer("input_tokens"),
  outputTokens: integer("output_tokens"),
  durationMs: integer("duration_ms"),
  errorCode: text("error_code"),
  metadata: jsonb("metadata").$type<Record<string, unknown>>().notNull().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  completedAt: timestamp("completed_at", { withTimezone: true }),
}, (table) => [
  uniqueIndex("agent_run_steps_run_number_unique_idx").on(table.runId, table.stepNumber),
  index("agent_run_steps_org_run_idx").on(table.organizationId, table.runId, table.createdAt),
  index("agent_run_steps_tool_call_idx").on(table.runId, table.toolCallId),
]);

export const agentRunCheckpoints = pgTable("agent_run_checkpoints", {
  id: uuid("id").defaultRandom().primaryKey(),
  organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  runId: uuid("run_id").notNull().references(() => runs.id, { onDelete: "cascade" }),
  version: integer("version").notNull(),
  encryptedState: text("encrypted_state").notNull(),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  uniqueIndex("agent_run_checkpoints_run_version_unique_idx").on(table.runId, table.version),
  index("agent_run_checkpoints_expiry_idx").on(table.expiresAt),
]);

export const toolApprovalsRuntime = pgTable("tool_approvals", {
  id: uuid("id").defaultRandom().primaryKey(),
  organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  runId: uuid("run_id").references(() => runs.id, { onDelete: "cascade" }),
  toolId: text("tool_id").notNull(),
  inputDigest: text("input_digest").notNull(),
  status: toolApprovalStatus("status").notNull().default("pending"),
  requestedByUserId: uuid("requested_by_user_id").references(() => users.id, { onDelete: "set null" }),
  decidedByUserId: uuid("decided_by_user_id").references(() => users.id, { onDelete: "set null" }),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  decidedAt: timestamp("decided_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  approvalId: text("approval_id").notNull(),
  toolCallId: text("tool_call_id"),
  serverId: uuid("server_id").references(() => mcpServers.id, { onDelete: "set null" }),
  agentId: uuid("agent_id").references(() => agents.id, { onDelete: "set null" }),
  encryptedArguments: text("encrypted_arguments"),
  reason: text("reason"),
  risk: text("risk"),
  capability: text("capability"),
  consumedAt: timestamp("consumed_at", { withTimezone: true }),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  uniqueIndex("tool_approvals_approval_id_unique_idx").on(table.approvalId),
  uniqueIndex("tool_approvals_run_tool_call_unique_idx").on(table.runId, table.toolCallId),
  index("tool_approvals_run_status_idx").on(table.organizationId, table.runId, table.status, table.expiresAt),
]);

export const mcpToolCallsRuntime = pgTable("mcp_tool_calls", {
  id: uuid("id").defaultRandom().primaryKey(),
  organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  serverId: uuid("server_id").notNull().references(() => mcpServers.id),
  toolId: uuid("tool_id").notNull().references(() => mcpTools.id),
  runId: uuid("run_id").references(() => runs.id, { onDelete: "set null" }),
  requestedByUserId: uuid("requested_by_user_id").references(() => users.id, { onDelete: "set null" }),
  inputDigest: text("input_digest").notNull(),
  status: text("status").notNull().default("running"),
  durationMs: integer("duration_ms"),
  result: jsonb("result").$type<Record<string, unknown>>(),
  errorCode: text("error_code"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  completedAt: timestamp("completed_at", { withTimezone: true }),
  toolCallId: text("tool_call_id"),
}, (table) => [
  uniqueIndex("mcp_tool_calls_run_tool_call_unique_idx").on(table.runId, table.toolCallId),
  index("mcp_tool_calls_org_created_idx").on(table.organizationId, table.createdAt),
]);

export const agentTeamRunsRuntime = pgTable("agent_team_runs", {
  id: uuid("id").defaultRandom().primaryKey(),
  organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  teamId: uuid("team_id").notNull(),
  requestedByUserId: uuid("requested_by_user_id").references(() => users.id, { onDelete: "set null" }),
  requestId: text("request_id").notNull(),
  input: text("input").notNull(),
  output: text("output"),
  status: text("status").notNull().default("queued"),
  errorCode: text("error_code"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  startedAt: timestamp("started_at", { withTimezone: true }),
  completedAt: timestamp("completed_at", { withTimezone: true }),
  graphileJobId: text("graphile_job_id"),
  cancelRequestedAt: timestamp("cancel_requested_at", { withTimezone: true }),
  retryRequestedAt: timestamp("retry_requested_at", { withTimezone: true }),
  attempts: integer("attempts").notNull().default(0),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  uniqueIndex("agent_team_runs_org_request_idx").on(table.organizationId, table.requestId),
  index("agent_team_runs_worker_status_idx").on(table.status, table.createdAt),
]);

export const agentTeamRunStepsRuntime = pgTable("agent_team_run_steps", {
  id: uuid("id").defaultRandom().primaryKey(),
  organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  teamRunId: uuid("team_run_id").notNull().references(() => agentTeamRuns.id, { onDelete: "cascade" }),
  agentId: uuid("agent_id").notNull().references(() => agents.id),
  runId: uuid("run_id").references(() => runs.id, { onDelete: "set null" }),
  stepType: text("step_type").notNull(),
  position: integer("position").notNull(),
  status: text("status").notNull().default("queued"),
  output: text("output"),
  errorCode: text("error_code"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  completedAt: timestamp("completed_at", { withTimezone: true }),
  stableRequestId: text("stable_request_id"),
  startedAt: timestamp("started_at", { withTimezone: true }),
  durationMs: integer("duration_ms"),
}, (table) => [
  uniqueIndex("agent_team_run_steps_identity_unique_idx").on(table.teamRunId, table.stepType, table.position),
  uniqueIndex("agent_team_run_steps_stable_request_unique_idx").on(table.organizationId, table.stableRequestId),
]);

export const workerHeartbeats = pgTable("worker_heartbeats", {
  workerId: text("worker_id").primaryKey(),
  startedAt: timestamp("started_at", { withTimezone: true }).defaultNow().notNull(),
  lastSeenAt: timestamp("last_seen_at", { withTimezone: true }).defaultNow().notNull(),
  stoppingAt: timestamp("stopping_at", { withTimezone: true }),
  metadata: jsonb("metadata").$type<Record<string, unknown>>().notNull().default({}),
}, (table) => [index("worker_heartbeats_last_seen_idx").on(table.lastSeenAt)]);
